import { useState, useRef, useEffect } from "react";
import { marked } from "marked";
import { useNavigate } from "react-router-dom";
import { useAITutor } from "../../context/AITutorContext";
import MathHTMLContainer from "../MathHTMLContainer/MathHTMLContainer";
import { getSuggestedQuestions } from "./tutorContextHelper";
import { generatePersonalLesson } from "../../services/api";

function cleanMath(math) {
  return math
    // Fix malformed subscripts generated by the model:
    // *{q_0} / *{q\_0} → _{q_0}
    .replace(/\\\*{(q\\?_?\d+)}/g, (_, qubit) => {
      return `\\_{${qubit.replace(/\\_/g, "_")}}`;
    })
    // Remove decorative semicolons around LaTeX operators:
    // ;\otimes; → \otimes
    // ;\longrightarrow; → \longrightarrow
    .replace(
      /;\s*(\\(?:otimes|longrightarrow|rightarrow|xrightarrow|cdot|times))\s*;/g,
      " $1 "
    );
}

function normalizeMathForMarkdown(text) {
  if (!text || typeof text !== "string") {
    return text || "";
  }

  let normalized = text;

  // Convert \\[...\\] → $$...$$
  normalized = normalized.replace(
    /\\\[([\s\S]*?)\\\]/g,
    (_, math) => `$$${cleanMath(math)}$$`
  );

  // Convert \\(...\\) → $...$
  normalized = normalized.replace(
    /\\\(([\s\S]*?)\\\)/g,
    (_, math) => `$${cleanMath(math)}$`
  );

  // Clean existing $$...$$ blocks
  normalized = normalized.replace(
    /\$\$([\s\S]*?)\$\$/g,
    (_, math) => `$$${cleanMath(math)}$$`
  );

  // Clean existing $...$ blocks
  normalized = normalized.replace(
    /(?<!\$)\$([^$\n]+?)\$(?!\$)/g,
    (_, math) => `$${cleanMath(math)}$`
  );

  return normalized;
}

function protectMathFromMarkdown(text) {
  const mathBlocks = [];

  const protectedText = text.replace(
    /\$\$[\s\S]*?\$\$|(?<!\$)\$[^$\n]*?\$(?!\$)/g,
    (match) => {
      const index = mathBlocks.length;
      mathBlocks.push(match);
      return `MATHBLOCK${index}END`;
    }
  );

  return {
    protectedText,
    mathBlocks,
  };
}

function restoreMathBlocks(html, mathBlocks) {
  let restored = html;

  mathBlocks.forEach((math, index) => {
    const token = `MATHBLOCK${index}END`;
    restored = restored.replace(token, escapeHtml(math));
  });

  return restored;
}

function escapeHtml(text) {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function Bubble({ role, text }) {
  const isUser = role === "user";

  if (isUser) {
    return (
      <div className="flex justify-end">
        <div
          className="max-w-[85%] rounded-2xl rounded-br-sm px-4 py-2.5 text-sm"
          style={{
            background: "var(--color-app-primary)",
            color: "#fff",
            border: "none",
          }}
        >
          <p className="whitespace-pre-wrap break-words">{text || ""}</p>
        </div>
      </div>
    );
  }

  const normalizedText = normalizeMathForMarkdown(text || "");
  const { protectedText, mathBlocks } = protectMathFromMarkdown(normalizedText);

  let html = marked.parse(protectedText);
  html = restoreMathBlocks(html, mathBlocks);

  return (
    <div className="flex justify-start">
      <div
        className="max-w-[95%] rounded-2xl rounded-bl-sm px-4 py-2.5 text-sm"
        style={{
          background: "var(--color-app-surface-hover)",
          color: "var(--color-app-text-main)",
          border: "1px solid var(--color-app-border)",
        }}
      >
        <MathHTMLContainer html={html} />
      </div>
    </div>
  );
}

export default function AITutorPanel() {
  const {
    isOpen,
    closeTutor,
    toggleTutor,
    activeContext,
    clearContext,
    messages,
    loading,
    error,
    lastFailedMessage,
    sendMessage,
    retryLastMessage,
  } = useAITutor();

  const navigate = useNavigate();
  const [input, setInput] = useState("");
  const [generatingLesson, setGeneratingLesson] = useState(false);
  const [genLessonNotice, setGenLessonNotice] = useState(null);
  const scrollRef = useRef(null);
  const inputRef = useRef(null);

  const currentTopicTitle = activeContext?.topic?.title || (activeContext?.query ? activeContext.query : null);

  const handleGeneratePersonalModule = async () => {
    if (!currentTopicTitle || generatingLesson) return;
    setGeneratingLesson(true);
    setGenLessonNotice(`✨ Generating your personal interactive lesson for "${currentTopicTitle}"...`);

    try {
      const userMsgs = messages.filter((m) => m.role === "user");
      const learnerIntent = userMsgs.length > 0 ? userMsgs[userMsgs.length - 1].text : "";

      const res = await generatePersonalLesson({
        topic: currentTopicTitle,
        topicDescription: activeContext?.topic?.description || "",
        forceAlternative: true, // Explicit user intent to turn this conversation/topic into a personal module
        conversation: messages.map((m) => ({ role: m.role, text: m.text })),
        learnerIntent,
      });

      if (res && res.lesson && res.lesson.lessonId) {
        setGenLessonNotice(null);
        setGeneratingLesson(false);
        closeTutor();
        navigate(`/generated-lessons/${res.lesson.lessonId}`);
      } else if (res && res.hasCurated && res.curatedResource) {
        setGenLessonNotice(null);
        setGeneratingLesson(false);
        navigate(res.curatedResource.route);
      }
    } catch (err) {
      console.error("Lesson generation from tutor failed:", err);
      setGenLessonNotice("⚠️ Could not generate lesson. Please try again.");
      setGeneratingLesson(false);
      setTimeout(() => setGenLessonNotice(null), 4000);
    }
  };

  // Auto scroll to bottom
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, loading, isOpen]);

  // Focus input on desktop
  useEffect(() => {
    if (isOpen && window.innerWidth >= 768 && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isOpen]);

  // Esc key listener
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape" && isOpen) {
        closeTutor();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [isOpen, closeTutor]);

  const handleSend = (textToSend = null) => {
    const text = (textToSend ?? input).trim();
    if (!text || loading) return;
    setInput("");
    sendMessage(text);
  };

  const suggestedQuestions = getSuggestedQuestions(activeContext);
  const contextTitle = activeContext?.topic?.title || activeContext?.resource?.title || (activeContext?.query ? `"${activeContext.query}"` : null);
  const contextSource = activeContext?.source || null;

  return (
    <>
      {/* Floating Launcher Button */}
      <button
        onClick={toggleTutor}
        className="fixed bottom-6 right-6 z-50 h-14 w-14 rounded-full shadow-2xl flex items-center justify-center transition-transform hover:scale-105 active:scale-95 cursor-pointer"
        style={{
          background:
            "linear-gradient(135deg, var(--color-app-primary), var(--color-app-accent))",
          boxShadow:
            "0 8px 30px var(--color-app-primary-glow)",
        }}
        aria-label={isOpen ? "Close AI Tutor" : "Open AI Tutor"}
        title="Ask Quantiva Tutor"
      >
        {isOpen ? (
          <svg
            width="22"
            height="22"
            fill="none"
            stroke="#fff"
            strokeWidth="2.2"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        ) : (
          <svg
            width="24"
            height="24"
            fill="none"
            stroke="#fff"
            strokeWidth="2"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
            />
          </svg>
        )}
      </button>

      {/* Floating Panel */}
      {isOpen && (
        <div
          className="fixed bottom-20 right-3 left-3 sm:left-auto sm:right-6 sm:bottom-24 z-50 w-auto sm:w-[26rem] max-w-full h-[calc(100vh-6.5rem)] sm:h-[36rem] max-h-[calc(100vh-7rem)] flex flex-col rounded-2xl overflow-hidden shadow-2xl border transition-all animate-fade-in"
          style={{
            background: "var(--color-app-surface)",
            borderColor: "var(--color-app-border)",
            boxShadow: "0 20px 60px rgba(0,0,0,0.45)",
          }}
          role="dialog"
          aria-modal="true"
          aria-label="Quantiva AI Tutor"
        >
          {/* Header */}
          <div
            className="flex items-center justify-between px-4 py-3 shrink-0"
            style={{
              borderBottom: "1px solid var(--color-app-border)",
            }}
          >
            <div className="flex items-center gap-2.5">
              <div
                className="h-8 w-8 rounded-lg flex items-center justify-center shrink-0"
                style={{
                  background:
                    "linear-gradient(135deg, var(--color-app-primary), var(--color-app-accent))",
                }}
              >
                <svg
                  width="16"
                  height="16"
                  fill="none"
                  stroke="#fff"
                  strokeWidth="2"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"
                  />
                </svg>
              </div>

              <div>
                <div
                  className="text-sm font-extrabold flex items-center gap-1.5"
                  style={{ color: "var(--color-app-text-main)" }}
                >
                  Ask Quantiva
                </div>
                <div
                  className="text-[10px] font-medium"
                  style={{ color: "var(--color-app-text-muted)" }}
                >
                  Contextual Quantum Tutor
                </div>
              </div>
            </div>

            <button
              onClick={closeTutor}
              className="p-1.5 rounded-lg hover:bg-white/10 transition-colors cursor-pointer"
              style={{ color: "var(--color-app-text-muted)" }}
              aria-label="Close panel"
            >
              <svg
                width="16"
                height="16"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>

          {/* Context Badge (When active context is present) */}
          {contextTitle && (
            <div
              className="px-4 py-2 flex items-center justify-between border-b text-xs shrink-0"
              style={{
                background: "rgba(99, 102, 241, 0.08)",
                borderColor: "var(--color-app-border)",
              }}
            >
              <div className="flex items-center gap-2 overflow-hidden">
                <span className="text-[10px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 shrink-0">
                  {contextSource || "Context"}
                </span>
                <span
                  className="font-semibold truncate text-[var(--color-app-text-main)]"
                  title={contextTitle}
                >
                  {contextTitle}
                </span>
                {activeContext?.topic?.category && (
                  <span className="text-[10px] text-[var(--color-app-text-muted)] shrink-0 hidden sm:inline">
                    · {activeContext.topic.category}
                  </span>
                )}
              </div>
              <button
                onClick={clearContext}
                title="Reset context to generic"
                className="text-[11px] text-[var(--color-app-text-muted)] hover:text-white ml-2 shrink-0 px-1.5 py-0.5 rounded hover:bg-white/10 transition-colors cursor-pointer"
                aria-label="Clear active context"
              >
                ✕
              </button>
            </div>
          )}

          {/* Messages Viewport */}
          <div
            ref={scrollRef}
            data-lenis-prevent="true"
            className="flex-1 overflow-y-auto p-4 space-y-3"
            style={{
              scrollBehavior: "smooth",
            }}
          >
            {messages.map((m, idx) => (
              <Bubble key={m.id || idx} role={m.role} text={m.text} />
            ))}

            {/* Thinking / Loading Indicator */}
            {loading && (
              <div className="flex justify-start">
                <div
                  className="rounded-2xl rounded-bl-sm px-4 py-2.5 text-xs flex items-center gap-2"
                  style={{
                    background: "var(--color-app-surface-hover)",
                    border: "1px solid var(--color-app-border)",
                    color: "var(--color-app-text-muted)",
                  }}
                >
                  <div className="flex gap-1 items-center">
                    <span className="ai-tutor-dot" />
                    <span
                      className="ai-tutor-dot"
                      style={{ animationDelay: "0.15s" }}
                    />
                    <span
                      className="ai-tutor-dot"
                      style={{ animationDelay: "0.3s" }}
                    />
                  </div>
                  <span className="font-medium text-[11px]">
                    Tutor is thinking...
                  </span>
                </div>
              </div>
            )}

            {/* Lesson Generation Indicator */}
            {generatingLesson && (
              <div className="flex justify-start">
                <div
                  className="rounded-2xl rounded-bl-sm px-4 py-2.5 text-xs flex items-center gap-2 border border-purple-500/30 bg-purple-500/10 text-purple-200"
                >
                  <span className="animate-spin text-sm">🌀</span>
                  <span className="font-semibold text-[11px]">
                    {genLessonNotice || "Generating your personal interactive lesson..."}
                  </span>
                </div>
              </div>
            )}

            {/* Error Banner with Retry */}
            {error && (
              <div
                className="text-xs px-3.5 py-2.5 rounded-xl flex items-center justify-between gap-2"
                style={{
                  background: "rgba(239, 68, 68, 0.12)",
                  color: "#f87171",
                  border: "1px solid rgba(239, 68, 68, 0.3)",
                }}
              >
                <div className="flex items-center gap-1.5 overflow-hidden">
                  <span>⚠️</span>
                  <span className="truncate">{error}</span>
                </div>
                {lastFailedMessage && (
                  <button
                    onClick={retryLastMessage}
                    className="px-2.5 py-1 rounded-lg text-[11px] font-bold bg-red-500/20 hover:bg-red-500/30 text-red-200 border border-red-500/40 shrink-0 transition-colors cursor-pointer"
                  >
                    Retry ↻
                  </button>
                )}
              </div>
            )}
          </div>

          {/* Explicit Personal Module Generation CTA (Only appears when context has an explicit topic) */}
          {currentTopicTitle && (
            <div
              className="px-4 py-2.5 flex items-center justify-between gap-3 border-t shrink-0"
              style={{
                background: "linear-gradient(135deg, rgba(168, 85, 247, 0.12), rgba(99, 102, 241, 0.08))",
                borderColor: "rgba(168, 85, 247, 0.25)",
              }}
            >
              <div className="text-[11px] font-semibold text-purple-200 truncate">
                Turn <strong className="text-white">"{currentTopicTitle}"</strong> into a lesson?
              </div>
              <button
                onClick={handleGeneratePersonalModule}
                disabled={generatingLesson || loading}
                className="px-3 py-1.5 rounded-xl text-xs font-bold text-white transition-all shadow-md hover:scale-105 active:scale-95 disabled:opacity-50 shrink-0 cursor-pointer flex items-center gap-1.5"
                style={{
                  background: "linear-gradient(135deg, #9333ea, #6366f1)",
                }}
                title="Generate as Your Own Micro-Module"
              >
                <span>⚡</span> Generate as Your Own Micro-Module
              </button>
            </div>
          )}

          {/* Suggested Starter Questions (when conversation has only initial greeting) */}
          {messages.length <= 1 && (
            <div
              className="px-4 pb-2 pt-1 flex flex-col gap-1.5 shrink-0 border-t"
              style={{
                borderColor: "var(--color-app-border)",
                background: "var(--color-app-surface)",
              }}
            >
              <div className="text-[11px] font-medium text-[var(--color-app-text-muted)] flex items-center gap-1">
                <span>💡</span> Suggested questions:
              </div>
              <div className="flex flex-wrap gap-1.5">
                {suggestedQuestions.map((q, idx) => (
                  <button
                    key={idx}
                    onClick={() => handleSend(q)}
                    disabled={loading}
                    className="text-left text-[11px] px-2.5 py-1 rounded-lg border transition-all hover:border-indigo-500/40 hover:bg-indigo-500/10 active:scale-[0.98] disabled:opacity-50 cursor-pointer"
                    style={{
                      borderColor: "var(--color-app-border)",
                      background: "var(--color-app-surface-hover)",
                      color: "var(--color-app-text-main)",
                    }}
                  >
                    {q}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Input Form */}
          <form
            className="flex items-center gap-2 p-3 shrink-0"
            style={{
              borderTop: "1px solid var(--color-app-border)",
              background: "var(--color-app-surface)",
            }}
            onSubmit={(e) => {
              e.preventDefault();
              handleSend();
            }}
          >
            <input
              ref={inputRef}
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              disabled={loading}
              placeholder={
                activeContext?.topic?.title
                  ? `Ask about ${activeContext.topic.title}...`
                  : "Ask about qubits, gates, algorithms..."
              }
              aria-label="Ask AI Tutor"
              className="flex-1 px-3.5 py-2 rounded-xl text-sm outline-none transition-colors disabled:opacity-60"
              style={{
                background: "var(--color-app-surface-hover)",
                border: "1px solid var(--color-app-border)",
                color: "var(--color-app-text-main)",
              }}
            />

            <button
              type="submit"
              disabled={loading || !input.trim()}
              aria-label="Send question"
              className="h-9 w-9 shrink-0 rounded-xl flex items-center justify-center disabled:opacity-40 transition-transform active:scale-95 cursor-pointer"
              style={{
                background:
                  "linear-gradient(135deg, var(--color-app-primary), var(--color-app-accent))",
                color: "#fff",
                boxShadow: "0 2px 8px var(--color-app-primary-glow)",
              }}
            >
              <svg
                width="16"
                height="16"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
                />
              </svg>
            </button>
          </form>
        </div>
      )}

      <style>{`
        .ai-tutor-dot {
          width: 5px;
          height: 5px;
          border-radius: 50%;
          background: var(--color-app-primary);
          animation: ai-tutor-bounce 1.2s infinite ease-in-out;
        }

        @keyframes ai-tutor-bounce {
          0%, 80%, 100% {
            transform: scale(0.6);
            opacity: 0.4;
          }
          40% {
            transform: scale(1.1);
            opacity: 1;
          }
        }
      `}</style>
    </>
  );
}
